[project]
name = "momentum-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.13.4",
    "matplotlib>=3.10.1",
    "polars>=1.29.0",
    "seaborn>=0.13.2",
]
